name: Build APK

on:
  push:
    branches:
      - 'main'  # Ensures the action runs on pushes to the main branch

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: 'Set up Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Set the Python version you need for your project

    - name: 'Cache Buildozer .buildozer directory'
      id: cache-buildozer
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          ~/.android
          ~/.buildozer
          ~/.gradle
          ~/.kivy
          ~/.cache/pip
        key: buildozer-${{ github.ref }}
        restore-keys: |
          buildozer-${{ github.ref }}
          buildozer-

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Build APK'
      run: |
        buildozer android debug
        #buildozer android release

    - name: 'Cache Buildozer .buildozer directory after build'
      if: always()
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          ~/.android
          ~/.buildozer
          ~/.gradle
          ~/.kivy
          ~/.cache/pip
        key: buildozer-${{ github.ref }}

    - name: 'Upload APK and AAB as Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: android
        path: bin/*
