name: Build APK

on:
  push:
    branches:
      - 'main'  # Ensures the action runs on pushes to the main branch

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: 'Set up Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Set the Python version you need for your project

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Build APK'
      run: |
        buildozer android debug
        #buildozer android release

    - name: 'List files'
      run: |
        pwd
        ls -hal 
        ls ~ -hal

    - name: 'Upload APK and AAB as Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: android
        path: bin/*
